name: Code Coverage

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@fa39846b074ac7a856c8af5f8c0dec12b1fff1aa
    secrets: inherit
    with:
      python_version: '3.11'
      coverage_source: 'json_database'
      test_path: 'test/'
      install_extras: 'test'
      min_coverage: 80
